#cloud-config
write_files:
  - path: /var/opt/jfrog/artifactory/etc/db.properties
    permissions: 0644
    content: |
      type=mysql
      driver=com.mysql.jdbc.Driver
      url=jdbc:mysql://${db_url}/${db_name}?characterEncoding=UTF-8&elideSetAutoCommits=true
      username=${db_user}
      password=${db_password}
  - path: /var/opt/jfrog/artifactory/etc/security/master.key
    permissions: 0644
    content: |
      ${master_key}
  - path: /var/opt/jfrog/artifactory/etc/ha-node.properties
    permissions: 0644
    content: |
      node.id=art1
      artifactory.ha.data.dir=/var/opt/jfrog/artifactory/data
      context.url=http://127.0.0.1:8081/artifactory
      membership.port=10001
      hazelcast.interface=172.25.0.3
      primary=true
  - path: /etc/nginx/conf.d/artifactory.conf
    permissions: 0777
    content: |
      ssl_certificate      /etc/pki/tls/certs/example.pem;
      ssl_certificate_key  /etc/pki/tls/private/example.key;
      ssl_session_cache shared:SSL:1m;
      ssl_prefer_server_ciphers   on;
      ## server configuration
      server {
        listen 443 ssl;
        listen 80 ;
        server_name ~(?<repo>.+)\.artifactory artifactory;
        if ($http_x_forwarded_proto = '') {
          set $http_x_forwarded_proto  $scheme;
        }
        ## Application specific logs
        ## access_log /var/log/nginx/artifactory-access.log timing;
        ## error_log /var/log/nginx/artifactory-error.log;
        rewrite ^/$ /artifactory/webapp/ redirect;
        rewrite ^/artifactory/?(/webapp)?$ /artifactory/webapp/ redirect;
        rewrite ^/(v1|v2)/(.*) /artifactory/api/docker/$repo/$1/$2;
        chunked_transfer_encoding on;
        client_max_body_size 0;
        location /artifactory/ {
          proxy_read_timeout  900;
          proxy_pass_header   Server;
          proxy_cookie_path   ~*^/.* /;
          proxy_pass          http://127.0.0.1:8081/artifactory/;
          proxy_set_header    X-Artifactory-Override-Base-Url
          $http_x_forwarded_proto://$host:$server_port/artifactory;
          proxy_set_header    X-Forwarded-Port  $server_port;
          proxy_set_header    X-Forwarded-Proto $http_x_forwarded_proto;
          proxy_set_header    Host              $http_host;
          proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
         }
      }
