#cloud-config
write_files:
  - path: /var/opt/jfrog/artifactory/etc/db.properties
    permissions: 0644
    content: |
      type=mysql
      driver=com.mysql.jdbc.Driver
      url=jdbc:mysql://${db_url}/${db_name}?characterEncoding=UTF-8&elideSetAutoCommits=true
      username=${db_user}
      password=${db_password}
  - path: /var/opt/jfrog/artifactory/etc/security/master.key
    permissions: 0644
    content: |
      ${master_key}