#cloud-config
write_files:
  - path: /var/opt/jfrog/artifactory/etc/db.properties
    permissions: 0644
    content: |
      type=mysql
      driver=com.mysql.jdbc.Driver
      url=jdbc:mysql://${db_url}/${db_name}?characterEncoding=UTF-8&elideSetAutoCommits=true
      username=${db_user}
      password=${db_password}
  - path: /var/opt/jfrog/artifactory/etc/security/master.key
    permissions: 0644
    content: |
      ${master_key}
  - path: /etc/pki/tls/certs/result.pem
    permissions: 0777
    content: |
      ${ssl_certificate}
  - path: /etc/pki/tls/private/result.key
    permissions: 0777
    content: |
      ${ssl_certificate_key}